# Generated by Django 5.2.8 on 2026-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tab_violations',
            field=models.IntegerField(default=0),
        ),
    ]
