# Generated by Django 5.2.8 on 2026-01-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_quizattempt_flagged_for_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='auto_submit_reason',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Time Up'), (2, 'Tab Switch')], default=0),
        ),
    ]
