# Generated by Django 5.2.8 on 2026-01-15 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_quizattempt_auto_submit_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveSmallIntegerField()),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Unvisited'), (1, 'Solved'), (2, 'Marked for Review'), (3, 'Skipped')], default=0)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
            ],
            options={
                'ordering': ['question_order'],
                'indexes': [models.Index(fields=['attempt', 'status'], name='quizzes_att_attempt_07e36e_idx'), models.Index(fields=['attempt', 'question_order'], name='quizzes_att_attempt_0c929a_idx')],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
