# Generated by Django 6.0.1 on 2026-01-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_attemptquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptquestion',
            unique_together={('attempt', 'question_order')},
        ),
        migrations.AlterField(
            model_name='attemptquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
    ]
