# Generated by Django 6.0.1 on 2026-01-19 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_allow_null_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('questions', models.JSONField(default=list)),
                ('time_limit_seconds', models.IntegerField(default=600)),
                ('share_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_quizzes', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_quiz_link', to='quizzes.quizattempt')),
                ('shared_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_attempts', to='quizzes.sharedquiz')),
            ],
        ),
        migrations.AddIndex(
            model_name='sharedquiz',
            index=models.Index(fields=['creator', 'created_at'], name='quizzes_sha_creator_9b2050_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedquiz',
            index=models.Index(fields=['share_code'], name='quizzes_sha_share_c_f3967f_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedquizattempt',
            index=models.Index(fields=['shared_quiz', 'accessed_at'], name='quizzes_sha_shared__f65c55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedquizattempt',
            unique_together={('shared_quiz', 'attempt')},
        ),
    ]
